# General labels
- name: 'semver:major'
  color: 'c10f47'
- name: 'semver:minor'
  color: 'e4f486'
- name: 'semver:patch'
  color: 'e8be8b'
- name: 'blocked'
  color: 'fc1423'
- name: 'question'
  color: 'd876e3'
- name: 'regression'
  color: 'ea8785'
- name: 'wontfix'
  color: 'ffffff'
- name: 'chore'
  color: 'ffffff'
- name: 'ci'
  color: '0075ca'
- name: 'dependencies'
  color: '276bd1'
- name: 'duplicate'
  color: 'cfd3d7'
- name: 'feature request'
  color: 'fcf95a'
- name: 'bug'
  color: 'd73a4a'
- name: 'backlog'
  color: '7ef7ef'
- name: 'good first issue'
  color: '7057ff'
- name: 'has PR'
  color: '4b1f8e'
- name: 'help wanted'
  color: '008672'
