chore:
  - changed-files:
      - all-globs-to-any-file: ['*', '!src/**/*']

ci:
  - changed-files:
      - any-glob-to-any-file: ['.github/**/*', '.husky/**/*', 'scripts/actions/**/*']

dependencies:
  - changed-files:
      - any-glob-to-any-file: ['package.json', 'pnpm-lock.yaml']
