name: Continuous Integration

on:
  push:
  pull_request:

jobs:
  testing:
    name: ESLint and TypeScript compilation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js v22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn
          registry-url: https://registry.yarnpkg.org/
      - name: Install dependencies
        run: yarn --immutable
      - name: Build project
        run: yarn build
      - name: ESLint check
        run: yarn lint
      - name: TypeScript check
        run: yarn build:check
